#ifndef XSANE_TEXT_H
#define XSANE_TEXT_H

#if ENABLE_NLS
/* comes later */
#else
# define gettext(Msgid) (Msgid)
# define dgettext(Domainname, Msgid) (Msgid)
# define dcgettext(Domainname, Msgid, Category) (Msgid)
# define textdomain(Domainname) ((char *) Domainname)
# define bindtextdomain(Domainname, Dirname) ((char *) Dirname) 
#endif

#define WINDOW_ABOUT			gettext("About")
#define WINDOW_AUTHORIZE		gettext("authorization")
#define WINDOW_INFO			gettext("info")
#define WINDOW_BATCH_SCAN		gettext("batch scan")
#define WINDOW_FAX_PROJECT		gettext("fax project")
#define WINDOW_FAX_RENAME		gettext("rename fax page")
#define WINDOW_SETUP			gettext("setup")
#define WINDOW_HISTOGRAM		gettext("Histogram")
#define WINDOW_STANDARD_OPTIONS		gettext("Standard options")
#define WINDOW_ADVANCED_OPTIONS		gettext("Advanced options")
#define WINDOW_DEVICE_SELECTION		gettext("device selection")
#define WINDOW_PREVIEW			gettext("preview")
#define WINDOW_OUTPUT_FILENAME		gettext("output filename")
#define WINDOW_SAVE_SETTINGS		gettext("save device settings")
#define WINDOW_LOAD_SETTINGS		gettext("load device settings")

#define MENU_FILE			gettext("File")
#define MENU_PREFERENCES		gettext("Preferences")
#define MENU_HELP			gettext("Help")

#define MENU_ITEM_ABOUT			gettext("About")
#define MENU_ITEM_INFO			gettext("Info")
#define MENU_ITEM_EXIT			gettext("Exit")

#define FRAME_RAW_IMAGE			gettext("Raw image")
#define FRAME_ENHANCED_IMAGE		gettext("Enhanced image")

#define BUTTON_START			gettext("Start")
#define BUTTON_PREVIEW			gettext("Preview Window")
#define BUTTON_OK			gettext("Ok")
#define BUTTON_APPLY			gettext("Apply")
#define BUTTON_CANCEL			gettext("Cancel")
#define BUTTON_CLOSE			gettext("Close")
#define BUTTON_ADD_AREA			gettext("Add area")
#define BUTTON_DELETE			gettext("Delete")
#define BUTTON_SHOW			gettext("Show")
#define BUTTON_RENAME			gettext("Rename")
#define BUTTON_SEND_PROJECT		gettext("Send project")
#define BUTTON_DELETE_PROJECT		gettext("Delete project")
#define BUTTON_ADD_PRINTER		gettext("Add printer")
#define BUTTON_DELETE_PRINTER		gettext("Delete printer")
#define BUTTON_PREVIEW_ACQUIRE		gettext("Acquire Preview")
#define BUTTON_PREVIEW_CANCEL		gettext("Cancel Preview")

#define RADIO_BUTTON_FINE_MODE		gettext("Fine mode")
#define RADIO_BUTTON_OVERWRITE_WARNING	gettext("Overwrite warning")
#define RADIO_BUTTON_INCREASE_COUNTER	gettext("Increase filename counter")
#define RADIO_BUTTON_SKIP_EXISTING_NRS	gettext("Skip existing numbers")
#define RADIO_BUTTON_WINDOW_FIXED	gettext("Main window size fixed")
#define RADIO_BUTTON_PRESERVE_PRVIEW	gettext("Preserve preview image")
#define RADIO_BUTTON_PRIVATE_COLORMAP	gettext("Use private colormap")

#define TEXT_AVAILABLE_DEVICES		gettext("Available devices:")
#define TEXT_XSANE_OPTIONS		gettext("XSane options")
#define TEXT_XSANE_MODE			gettext("XSane mode")
#define TEXT_SET_ENHANCEMENT		gettext("Set enhancement:")
#define TEXT_SCANNER_BACKEND		gettext("Scanner and backend:")
#define TEXT_VENDOR			gettext("Vendor:")
#define TEXT_MODEL			gettext("Model:")
#define TEXT_TYPE			gettext("Type:")
#define TEXT_DEVICE			gettext("Device:")
#define TEXT_LOADED_BACKEND		gettext("Loaded backend:")
#define TEXT_SANE_VERSION		gettext("Sane version:")
#define TEXT_RECENT_VALUES		gettext("Recent values:")
#define TEXT_GAMMA_CORR_BY		gettext("Gamma correction by:")
#define TEXT_SCANNER			gettext("scanner")
#define TEXT_SOFTWARE_XSANE		gettext("software (xsane)")
#define TEXT_NONE			gettext("none")
#define TEXT_GAMMA_INPUT_DEPTH		gettext("Gamma input depth:")
#define TEXT_GAMMA_OUTPUT_DEPTH		gettext("Gamma output depth:")
#define TEXT_SCANNER_OUTPUT_DEPTH	gettext("Scanner output depth:")
#define TEXT_OUTPUT_FORMATS		gettext("XSane output formats:")
#define TEXT_8BIT_FORMATS		gettext("8 bit output formats:")
#define TEXT_16BIT_FORMATS		gettext("16 bit output formats:")
#define TEXT_AUTHORIZATION_REQ		gettext("Authorization required for")
#define TEXT_USERNAME			gettext("Username :")
#define TEXT_PASSWORD			gettext("Password :")
#define TEXT_INVALID_PARAMS		gettext("Invalid parameters.")
#define TEXT_VERSION			gettext("version:")

#define TEXT_SETUP_PRINTER_SEL		gettext("Printer selection:")
#define TEXT_SETUP_PRINTER_NAME		gettext("Name:")
#define TEXT_SETUP_PRINTER_CMD		gettext("Command:")
#define TEXT_SETUP_COPY_NR_OPT		gettext("Copy number option:")
#define TEXT_SETUP_PRINTER_RES		gettext("Resolution (dpi):")
#define TEXT_SETUP_PRINTER_WIDTH	gettext("Width (1/72 inch):")
#define TEXT_SETUP_PRINTER_HEIGHT	gettext("Height (1/72 inch):")
#define TEXT_SETUP_PRINTER_LEFT		gettext("Left offset (1/72 inch):")
#define TEXT_SETUP_PRINTER_BOTTOM	gettext("Bottom offset (1/72 inch):")
#define TEXT_SETUP_PRINTER_GAMMA	gettext("Printer gamma value:")
#define TEXT_SETUP_PRINTER_GAMMA_RED	gettext("Printer gamma red:")
#define TEXT_SETUP_PRINTER_GAMMA_GREEN	gettext("Printer gamma green:")
#define TEXT_SETUP_PRINTER_GAMMA_BLUE	gettext("Printer gamma blue:")
#define TEXT_SETUP_JPEG_QUALITY		gettext("JPEG image quality")
#define TEXT_SETUP_PNG_COMPRESSION	gettext("PNG image compression")
#define TEXT_SETUP_TIFF_COMPRESSION	gettext("TIFF multi bit image compression")
#define TEXT_SETUP_TIFF_COMPRESSION_1	gettext("TIFF lineart image compression")
#define TEXT_SETUP_PREVIEW_GAMMA	gettext("Preview gamma:")
#define TEXT_SETUP_PREVIEW_GAMMA_RED	gettext("Preview gamma red:")
#define TEXT_SETUP_PREVIEW_GAMMA_GREEN	gettext("Preview gamma green:")
#define TEXT_SETUP_PREVIEW_GAMMA_BLUE	gettext("Preview gamma blue:")
#define TEXT_SETUP_HELPFILE_VIEWER	gettext("Helpfile viewer (HTML):")
#define TEXT_SETUP_FAX_COMMAND		gettext("Command:")
#define TEXT_SETUP_FAX_RECEIVER_OPTION	gettext("Receiver option:")
#define TEXT_SETUP_FAX_POSTSCRIPT_OPT	gettext("Postscriptfile option:")
#define TEXT_SETUP_FAX_NORMAL_MODE_OPT	gettext("Normal mode option:")
#define TEXT_SETUP_FAX_FINE_MODE_OPT	gettext("Fine mode option:")
#define TEXT_SETUP_FAX_VIEWER		gettext("Viewer (Postscript):")

#define NOTEBOOK_PRINTER_OPTIONS	gettext("Printer options")
#define NOTEBOOK_SAVING_OPTIONS		gettext("Saving options")
#define NOTEBOOK_DISPLAY_OPTIONS	gettext("Display options")
#define NOTEBOOK_FAX_OPTIONS		gettext("Fax options")

#define MENU_ITEM_SCAN			gettext("Scan")
#define MENU_ITEM_COPY			gettext("Copy")
#define MENU_ITEM_FAX			gettext("Fax")

#define MENU_ITEM_TIFF_COMP_NONE	gettext("no compression")
#define MENU_ITEM_TIFF_COMP_CCITTRLE	gettext("CCITT 1D Huffman compression")
#define MENU_ITEM_TIFF_COMP_CCITFAX3	gettext("CCITT Group 3 Fax compression")
#define MENU_ITEM_TIFF_COMP_CCITFAX4	gettext("CCITT Group 4 Fax compression")
#define MENU_ITEM_TIFF_COMP_LZW		gettext("Lempel-Ziv & Welch compression")
#define MENU_ITEM_TIFF_COMP_JPEG	gettext("JPEG DCT compression")
#define MENU_ITEM_TIFF_COMP_PACKBITS	gettext("pack bits")

#define MENU_ITEM_FILETYPE_JPEG		gettext(".jpeg")
#define MENU_ITEM_FILETYPE_PNG		gettext(".png")
#define MENU_ITEM_FILETYPE_PNM		gettext(".pnm")
#define MENU_ITEM_FILETYPE_PS		gettext(".ps")
#define MENU_ITEM_FILETYPE_RAW		gettext(".raw")
#define MENU_ITEM_FILETYPE_TIFF		gettext(".tiff")
#define MENU_ITEM_FILETYPE_BY_EXT	gettext("by ext")


#define DESC_XSANE_MODE			gettext("Use XSane for SCANning, photoCOPYing, FAXing...")

#define DESC_BROWSE_FILENAME		gettext("Browse for image filename")
#define DESC_FILENAME			gettext("Filename for scanned image")
#define DESC_FILETYPE			gettext("Define image file format")
#define DESC_FAXPROJECT			gettext("Enter name of fax project")
#define DESC_FAXPAGENAME		gettext("Enter new name for faxpage")
#define DESC_FAXRECEIVER		gettext("Enter receiver phone number or address")

#define DESC_PRINTER_SELECT		gettext("Select printer definition")

#define DESC_RESOLUTION			gettext("Set scan resolution")
#define DESC_ZOOM			gettext("Set zoomfactor")
#define DESC_COPY_NUMBER		gettext("Set number of copies")

#define DESC_NEGATIVE			gettext("Negative: Invert colors for scanning negatives\n" \
						"e.g. swap black and white")

#define DESC_GAMMA			gettext("Set gamma value")
#define DESC_GAMMA_R			gettext("Set gamma value for red component")
#define DESC_GAMMA_G			gettext("Set gamma value for green component")
#define DESC_GAMMA_B			gettext("Set gamma value for blue component")

#define DESC_BRIGHTNESS			gettext("Set brightness")
#define DESC_BRIGHTNESS_R		gettext("Set brightness for red component")
#define DESC_BRIGHTNESS_G		gettext("Set brightness for green component")
#define DESC_BRIGHTNESS_B		gettext("Set brightness for blue component")

#define DESC_CONTRAST			gettext("Set contrast")
#define DESC_CONTRAST_R			gettext("Set contrast for red component")
#define DESC_CONTRAST_G			gettext("Set contrast for green component")
#define DESC_CONTRAST_B			gettext("Set contrast for blue component")

#define DESC_RGB_DEFAULT		gettext("RGB default: Set enhancement values for red, green and blue to default values:\n" \
						" gamma = 1.0\n" \
						" brightness = 0\n" \
						" contrast = 0")

#define DESC_WHITE			gettext("Define intensity that shall be transformed to white")
#define DESC_GRAY			gettext("Define intensity that shall be transformed to medium gray")
#define DESC_BLACK			gettext("Define intensity that shall be transformed to black")

#define DESC_ENH_AUTO			gettext("Autoadjust gamma, brightness and contrast in dependance " \
						"of selected area (rgb-values are set to default)")
#define DESC_ENH_DEFAULT		gettext("Set default enhancement values:\n" \
						"gamma = 1.0\n" \
						"brightness = 0\n" \
						"contrast = 0")
#define DESC_ENH_RESTORE		gettext("Restore enhancement values from preferences")
#define DESC_ENH_STORE			gettext("Store active enhancemnt values to preferences")

#define DESC_HIST_INTENSITY		gettext("Show histogram of intensity/gray")
#define DESC_HIST_RED			gettext("Show histogram of red component")
#define DESC_HIST_GREEN			gettext("Show histogram of green component")
#define DESC_HIST_BLUE			gettext("Show histogram of blue component")
#define DESC_HIST_PIXEL			gettext("Display histogram with lines instead of pixels")
#define DESC_HIST_LOG			gettext("Show logarithm of pixelcount")

#define DESC_PRINTER_SETUP		gettext("Select definition to change")
#define DESC_PRINTER_NAME		gettext("Define a name for the selection of this definition")
#define DESC_PRINTER_COMMAND		gettext("Enter command to be executed in copy mode (e.g. \"lpr -\")")
#define DESC_COPY_NUMBER_OPTION		gettext("Enter option for copy numbers")
#define DESC_PRINTER_RESOLUTION		gettext("Resolution with which images are printed and saved in postscript")
#define DESC_PRINTER_WIDTH		gettext("Width of printable area in 1/72 inch")
#define DESC_PRINTER_HEIGHT		gettext("Height of printable area in 1/72 inch")
#define DESC_PRINTER_LEFTOFFSET		gettext("Left offset from the edge of the paper to the printable area in 1/72 inch")
#define DESC_PRINTER_BOTTOMOFFSET	gettext("Bottom offset from the edge of the paper to the printable area in 1/72 inch")
#define DESC_PRINTER_GAMMA		gettext("Additional gamma value for photocopy")
#define DESC_PRINTER_GAMMA_RED		gettext("Additional gamma value for red component for photocopy")
#define DESC_PRINTER_GAMMA_GREEN	gettext("Additional gamma value for green component for photocopy")
#define DESC_PRINTER_GAMMA_BLUE		gettext("Additional gamma value for blue component for photocopy")
#define DESC_JPEG_QUALITY		gettext("Quality in percent if image is saved as jpeg or tiff with jpeg compression")
#define DESC_PNG_COMPRESSION		gettext("Compression if image is saved as png")
#define DESC_TIFF_COMPRESSION		gettext("Compression type if multi bit image is saved as tiff")
#define DESC_TIFF_COMPRESSION_1		gettext("Compression type if lineart image is saved as tiff")
#define DESC_OVERWRITE_WARNING		gettext("Warn before overwriting an existing file")
#define DESC_INCREASE_COUNTER		gettext("If the filename is of the form \"name-001.ext\" " \
						"(where the number of digits is free) " \
						"the number is increased after a scan is finished")
#define DESC_SKIP_EXISTING		gettext("If filename counter is automatically increased, used numbers are skipped")
#define DESC_MAIN_WINDOW_FIXED		gettext("Use fixed main window size or scrolled, resizable main window")
#define DESC_PREVIEW_PRESERVE		gettext("Preserve preview image for next program start")
#define DESC_PREVIEW_COLORMAP		gettext("Use an own colormap for preview if display depth is 8 bpp")
#define DESC_PREVIEW_GAMMA		gettext("Set gamma correction value for preview image")
#define DESC_PREVIEW_GAMMA_RED		gettext("Set gamma correction value for red component of preview image")
#define DESC_PREVIEW_GAMMA_GREEN	gettext("Set gamma correction value for green component of preview image")
#define DESC_PREVIEW_GAMMA_BLUE		gettext("Set gamma correction value for blue component of preview image")
#define DESC_DOC_VIEWER			gettext("Enter command to be executed to display helpfiles, must be a html-viewer!")

#define DESC_FAX_COMMAND		gettext("Enter command to be executed in fax mode")
#define DESC_FAX_RECEIVER_OPT		gettext("Enter option to specify receiver")
#define DESC_FAX_POSTSCRIPT_OPT		gettext("Enter option to specify postscript files following")
#define DESC_FAX_NORMAL_OPT		gettext("Enter option to specify normal mode (low resolution)")
#define DESC_FAX_FINE_OPT		gettext("Enter option to specify fine mode (high resolution)")
#define DESC_FAX_VIEWER			gettext("Enter command to be executed to view a fax")
#define DESC_FAX_FINE_MODE		gettext("Use high vertical resolution (196 lpi instead of 98 lpi)")

#define DESC_PIPETTE_WHITE		gettext("Pick white point")
#define DESC_PIPETTE_GRAY		gettext("Pick gray point")
#define DESC_PIPETTE_BLACK		gettext("Pick black point")

#define DESC_ZOOM_FULL			gettext("Use full scanarea")
#define DESC_ZOOM_OUT			gettext("Zoom 20% out")
#define DESC_ZOOM_IN			gettext("Zoom into selected area")
#define DESC_ZOOM_UNDO			gettext("Undo last zoom")

#define DESC_FULL_PREVIEW_AREA		gettext("Select visible area")


#define ERR_HOME_DIR			gettext("Failed to determine home directory:")
#define ERR_FILENAME_TOO_LONG		gettext("Filename too long")
#define ERR_SET_OPTION			gettext("Failed to set value of option")
#define ERR_GET_OPTION			gettext("Failed to obtain value of option")
#define ERR_OPTION_COUNT		gettext("Error obtaining option count")

#define ERR_BUTTON_OK			gettext("Ok")
#define ERR_HEADER_ERROR		gettext("Error")
#define ERR_HEADER_WARNING		gettext("Warning")

#endif
