/* Sane backend messages */
_("flatbed scanner")
_("frame grabber")
_("handheld scanner")
_("still camera")
_("video camera")
_("virtual device")
_("Success")
_("Operation not supported")
_("Operation was cancelled")
_("Device busy")
_("Invalid argument")
_("End of file reached")
_("Document feeder jammed")
_("Document feeder out of documents")
_("Scanner cover is open")
_("Error during device I/O")
_("Out of memory")
_("Access to resource has been denied")
