s/WINDOW_ABOUT_TRANSLATION/&, MENU_ITEM_ABOUT_TRANSLATION/
s/TEXT_SETUP_PRINTER_CMD/&, TEXT_SETUP_FAX_CMD/
#s/BUTTON_OK/&, BUTTON_OK/
s@DESC_ZOOM_OUT@xgettext:no-c-format */ /*&@
s@DESC_PREVIEW_THRESHOLD_MIN@xgettext:no-c-format */ /*&@
s@DESC_PREVIEW_THRESHOLD_MAX@xgettext:no-c-format */ /*&@
